"""empty message

Revision ID: 454d8b8be036
Revises: 4da855c7f9a1
Create Date: 2022-12-30 16:52:25.567209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454d8b8be036'
down_revision = '4da855c7f9a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
